#!/usr/bin/env bash
# This script installs nginx on the computer it's run on.
#  It prints 'Hello world' when curled
# It also redirects query to /redirect_me to YouTube
apt-get update
apt-get -y install nginx
echo 'Hello World!' | tee /var/www/html/index.nginx-debian.html
ufw allow 'Nginx HTTP'
sed -i '/^\tserver_name _.*/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
