#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

sudo apt install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7.0
sudo apt update
sudo apt install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.orig
sudo touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 94865-web-01 54.89.32.73:80 check
    server 94865-web-02 35.175.130.231:80 check
frontend haproxy-main
    bind *:80
    option forwardfor  
    default_backend webserver    

backend webserver
    balance roundrobin
    server 94865-web-01 54.89.32.73:80 check
    server 94865-web-02 35.175.130.231:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start