#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

sudo apt install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7.0
sudo apt update
sudo apt install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.orig

echo "
frontend haproxy-main
    bind 0.0.0.0:80
    option forwardfor  
    default_backend webserver    

backend webserver
    balance roundrobin
    server 94865-web-01 54.89.32.73:80 check
    server 94865-web-02 35.175.130.231:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy start
