#!/usr/bin/env bash
#a Bash script that displays Best School 10 times, 
#but for the 9th iteration, displays Best School 
#and then Hi on a new line.
i=1
while ((i <= 10))
do
    echo "Best school"
    if ((i == 9))
    then
        echo "Hi"
    fi
    ((i++))
done